spring:
  kafka:
    properties:
      schema.registry.url: http://localhost:8081
  cloud:
    stream:
      bindings:
        eventStream-in-0:
          destination: inputTopic
          group: group1
        eventStream-out-0:
          destination: outputTopic
          group: group1
      kafka:
        binder:
          brokers: localhost:9092
          consumer-properties:
            specific.avro.reader: true
        streams:
          binder:
            configuration:
              default:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde